version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de autenticación
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./auth-service/.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Servicio de usuarios
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Servicio de posts
  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Frontend Vue.js
  frontend:
    build:
      context: ./red-social-vue
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - user-service
      - post-service
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    driver: bridge