version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Servicio de autenticación
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./auth-service/.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=auth_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - NODE_ENV=production

  # Servicio de usuarios
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./user-service/.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=user_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  # Servicio de posts
  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./post-service/.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=post_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  # Frontend Vue.js
  frontend:
    build:
      context: ./red-social-vue
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - user-service
      - post-service
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - VITE_AUTH_SERVICE_URL=http://auth-service:3001
      - VITE_USER_SERVICE_URL=http://user-service:3002
      - VITE_POST_SERVICE_URL=http://post-service:3003

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge